package state

import "fmt"

func laterBeginner200Groups() []beginnerKanjiGroup {
	return []beginnerKanjiGroup{
		{
			Number: 6,
			Title:  "Language And Reading",
			Kanji: []beginnerKanjiSeed{
				b200Kanji("名", "な", "na", "name", "名前", "なまえ", "namae", "name"),
				b200Kanji("国", "くに", "kuni", "country", "国", "くに", "kuni", "country"),
				b200Kanji("語", "ご", "go", "language", "日本語", "にほんご", "nihongo", "Japanese language"),
				b200Kanji("本", "ほん", "hon", "book; origin", "本", "ほん", "hon", "book"),
				b200Kanji("書", "か", "ka", "write", "書きます", "かきます", "kakimasu", "write"),
				b200Kanji("読", "よ", "yo", "read", "読みます", "よみます", "yomimasu", "read"),
				b200Kanji("聞", "き", "ki", "listen; ask", "聞きます", "ききます", "kikimasu", "listen; ask"),
				b200Kanji("話", "はな", "hana", "speak; story", "話します", "はなします", "hanashimasu", "speak"),
				b200Kanji("見", "み", "mi", "see", "見ます", "みます", "mimasu", "see; watch"),
				b200Kanji("行", "い", "i", "go", "行きます", "いきます", "ikimasu", "go"),
			},
			Sentences: []beginnerSentenceSeed{
				b200Sentence("日本語の本を読みます", "にほんごのほんをよみます", "nihongo no hon o yomimasu", "I read a Japanese-language book."),
				b200Sentence("名前を書きます", "なまえをかきます", "namae o kakimasu", "I write my name."),
				b200Sentence("国の話を聞きます", "くにのはなしをききます", "kuni no hanashi o kikimasu", "I listen to a story about a country."),
				b200Sentence("日本語を話します", "にほんごをはなします", "nihongo o hanashimasu", "I speak Japanese."),
				b200Sentence("学校へ行きます", "がっこうへいきます", "gakkou e ikimasu", "I go to school."),
			},
		},
		{
			Number: 7,
			Title:  "Daily Actions",
			Kanji: []beginnerKanjiSeed{
				b200Kanji("来", "き", "ki", "come", "来ます", "きます", "kimasu", "come"),
				b200Kanji("帰", "かえ", "kae", "return", "帰ります", "かえります", "kaerimasu", "return home"),
				b200Kanji("食", "た", "ta", "eat", "食べます", "たべます", "tabemasu", "eat"),
				b200Kanji("飲", "の", "no", "drink", "飲みます", "のみます", "nomimasu", "drink"),
				b200Kanji("買", "か", "ka", "buy", "買います", "かいます", "kaimasu", "buy"),
				b200Kanji("出", "で", "de", "exit; leave", "出ます", "でます", "demasu", "leave; appear"),
				b200Kanji("入", "はい", "hai", "enter", "入ります", "はいります", "hairimasu", "enter"),
				b200Kanji("休", "やす", "yasu", "rest", "休みます", "やすみます", "yasumimasu", "rest"),
				b200Kanji("会", "あ", "a", "meet", "会います", "あいます", "aimasu", "meet"),
				b200Kanji("社", "しゃ", "sha", "company", "会社", "かいしゃ", "kaisha", "company"),
			},
			Sentences: []beginnerSentenceSeed{
				b200Sentence("会社へ行きます", "かいしゃへいきます", "kaisha e ikimasu", "I go to the company."),
				b200Sentence("水を飲みます", "みずをのみます", "mizu o nomimasu", "I drink water."),
				b200Sentence("本を買います", "ほんをかいます", "hon o kaimasu", "I buy a book."),
				b200Sentence("家に帰ります", "いえにかえります", "ie ni kaerimasu", "I return home."),
				b200Sentence("友達に会います", "ともだちにあいます", "tomodachi ni aimasu", "I meet a friend."),
			},
		},
		{
			Number: 8,
			Title:  "Places And Weather",
			Kanji: []beginnerKanjiSeed{
				b200Kanji("店", "みせ", "mise", "shop", "店", "みせ", "mise", "shop"),
				b200Kanji("駅", "えき", "eki", "station", "駅", "えき", "eki", "station"),
				b200Kanji("車", "くるま", "kuruma", "car", "車", "くるま", "kuruma", "car"),
				b200Kanji("電", "でん", "den", "electricity", "電車", "でんしゃ", "densha", "train"),
				b200Kanji("山", "やま", "yama", "mountain", "山", "やま", "yama", "mountain"),
				b200Kanji("川", "かわ", "kawa", "river", "川", "かわ", "kawa", "river"),
				b200Kanji("田", "た", "ta", "rice field", "田んぼ", "たんぼ", "tanbo", "rice field"),
				b200Kanji("天", "てん", "ten", "sky; heaven", "天気", "てんき", "tenki", "weather"),
				b200Kanji("気", "き", "ki", "spirit; air", "天気", "てんき", "tenki", "weather"),
				b200Kanji("雨", "あめ", "ame", "rain", "雨", "あめ", "ame", "rain"),
			},
			Sentences: []beginnerSentenceSeed{
				b200Sentence("駅で電車を見ます", "えきででんしゃをみます", "eki de densha o mimasu", "I see a train at the station."),
				b200Sentence("店で車を見ます", "みせでくるまをみます", "mise de kuruma o mimasu", "I see a car at the shop."),
				b200Sentence("山と川があります", "やまとかわがあります", "yama to kawa ga arimasu", "There are mountains and a river."),
				b200Sentence("今日は雨です", "きょうはあめです", "kyou wa ame desu", "Today is rainy."),
				b200Sentence("田んぼへ行きます", "たんぼへいきます", "tanbo e ikimasu", "I go to the rice field."),
			},
		},
		{
			Number: 9,
			Title:  "Nature And Animals",
			Kanji: []beginnerKanjiSeed{
				b200Kanji("雪", "ゆき", "yuki", "snow", "雪", "ゆき", "yuki", "snow"),
				b200Kanji("火", "ひ", "hi", "fire", "火", "ひ", "hi", "fire"),
				b200Kanji("水", "みず", "mizu", "water", "水", "みず", "mizu", "water"),
				b200Kanji("木", "き", "ki", "tree", "木", "き", "ki", "tree"),
				b200Kanji("金", "かね", "kane", "money; gold", "お金", "おかね", "okane", "money"),
				b200Kanji("土", "つち", "tsuchi", "soil", "土", "つち", "tsuchi", "soil"),
				b200Kanji("花", "はな", "hana", "flower", "花", "はな", "hana", "flower"),
				b200Kanji("魚", "さかな", "sakana", "fish", "魚", "さかな", "sakana", "fish"),
				b200Kanji("犬", "いぬ", "inu", "dog", "犬", "いぬ", "inu", "dog"),
				b200Kanji("白", "しろ", "shiro", "white", "白い", "しろい", "shiroi", "white"),
			},
			Sentences: []beginnerSentenceSeed{
				b200Sentence("雪と雨を見ます", "ゆきとあめをみます", "yuki to ame o mimasu", "I see snow and rain."),
				b200Sentence("犬は水を飲みます", "いぬはみずをのみます", "inu wa mizu o nomimasu", "The dog drinks water."),
				b200Sentence("白い花があります", "しろいはながあります", "shiroi hana ga arimasu", "There is a white flower."),
				b200Sentence("魚を食べます", "さかなをたべます", "sakana o tabemasu", "I eat fish."),
				b200Sentence("木の下で休みます", "きのしたでやすみます", "ki no shita de yasumimasu", "I rest under a tree."),
			},
		},
		{
			Number: 10,
			Title:  "Colors And Qualities",
			Kanji: []beginnerKanjiSeed{
				b200Kanji("黒", "くろ", "kuro", "black", "黒い", "くろい", "kuroi", "black"),
				b200Kanji("赤", "あか", "aka", "red", "赤い", "あかい", "akai", "red"),
				b200Kanji("青", "あお", "ao", "blue", "青い", "あおい", "aoi", "blue"),
				b200Kanji("安", "やす", "yasu", "cheap; safe", "安い", "やすい", "yasui", "cheap"),
				b200Kanji("高", "たか", "taka", "high; expensive", "高い", "たかい", "takai", "high; expensive"),
				b200Kanji("新", "あたら", "atara", "new", "新しい", "あたらしい", "atarashii", "new"),
				b200Kanji("古", "ふる", "furu", "old", "古い", "ふるい", "furui", "old"),
				b200Kanji("長", "なが", "naga", "long", "長い", "ながい", "nagai", "long"),
				b200Kanji("多", "おお", "oo", "many", "多い", "おおい", "ooi", "many"),
				b200Kanji("少", "すく", "suku", "few", "少ない", "すくない", "sukunai", "few; little"),
			},
			Sentences: []beginnerSentenceSeed{
				b200Sentence("新しい本を買います", "あたらしいほんをかいます", "atarashii hon o kaimasu", "I buy a new book."),
				b200Sentence("古い車を見ます", "ふるいくるまをみます", "furui kuruma o mimasu", "I see an old car."),
				b200Sentence("赤い花があります", "あかいはながあります", "akai hana ga arimasu", "There is a red flower."),
				b200Sentence("高い店へ行きます", "たかいみせへいきます", "takai mise e ikimasu", "I go to an expensive shop."),
				b200Sentence("水が少ないです", "みずがすくないです", "mizu ga sukunai desu", "There is little water."),
			},
		},
		{
			Number: 11,
			Title:  "Home Address And Town",
			Kanji: []beginnerKanjiSeed{
				b200Kanji("早", "はや", "haya", "early", "早い", "はやい", "hayai", "early; fast"),
				b200Kanji("午", "ご", "go", "noon", "午前", "ごぜん", "gozen", "morning; a.m."),
				b200Kanji("間", "あいだ", "aida", "interval; between", "時間", "じかん", "jikan", "time"),
				b200Kanji("私", "わたし", "watashi", "I; me", "私", "わたし", "watashi", "I; me"),
				b200Kanji("主", "しゅ", "shu", "main; master", "主人", "しゅじん", "shujin", "household head; husband"),
				b200Kanji("住", "す", "su", "live", "住みます", "すみます", "sumimasu", "live"),
				b200Kanji("所", "ところ", "tokoro", "place", "住所", "じゅうしょ", "juusho", "address"),
				b200Kanji("町", "まち", "machi", "town", "町", "まち", "machi", "town"),
				b200Kanji("村", "むら", "mura", "village", "村", "むら", "mura", "village"),
				b200Kanji("市", "し", "shi", "city", "市", "し", "shi", "city"),
			},
			Sentences: []beginnerSentenceSeed{
				b200Sentence("私は町に住みます", "わたしはまちにすみます", "watashi wa machi ni sumimasu", "I live in a town."),
				b200Sentence("住所を書きます", "じゅうしょをかきます", "juusho o kakimasu", "I write an address."),
				b200Sentence("早い時間に行きます", "はやいじかんにいきます", "hayai jikan ni ikimasu", "I go at an early time."),
				b200Sentence("村から市へ行きます", "むらからしへいきます", "mura kara shi e ikimasu", "I go from a village to a city."),
				b200Sentence("午前に店へ行きます", "ごぜんにみせへいきます", "gozen ni mise e ikimasu", "I go to the shop in the morning."),
			},
		},
		{
			Number: 12,
			Title:  "Rooms And Wide Places",
			Kanji: []beginnerKanjiSeed{
				b200Kanji("都", "と", "to", "metropolis", "東京都", "とうきょうと", "toukyou to", "Tokyo Metropolis"),
				b200Kanji("道", "みち", "michi", "road; way", "道", "みち", "michi", "road"),
				b200Kanji("京", "きょう", "kyou", "capital", "東京", "とうきょう", "toukyou", "Tokyo"),
				b200Kanji("海", "うみ", "umi", "sea", "海", "うみ", "umi", "sea"),
				b200Kanji("空", "そら", "sora", "sky", "空", "そら", "sora", "sky"),
				b200Kanji("家", "いえ", "ie", "house; home", "家", "いえ", "ie", "home"),
				b200Kanji("室", "しつ", "shitsu", "room", "教室", "きょうしつ", "kyoushitsu", "classroom"),
				b200Kanji("部", "ぶ", "bu", "section; club", "部活", "ぶかつ", "bukatsu", "club activity"),
				b200Kanji("屋", "や", "ya", "shop; room", "部屋", "へや", "heya", "room"),
				b200Kanji("門", "もん", "mon", "gate", "門", "もん", "mon", "gate"),
			},
			Sentences: []beginnerSentenceSeed{
				b200Sentence("東京の道を見ます", "とうきょうのみちをみます", "toukyou no michi o mimasu", "I look at a Tokyo road."),
				b200Sentence("海と空を見ます", "うみとそらをみます", "umi to sora o mimasu", "I look at the sea and sky."),
				b200Sentence("家の部屋で休みます", "いえのへやでやすみます", "ie no heya de yasumimasu", "I rest in a room at home."),
				b200Sentence("教室に入ります", "きょうしつにはいります", "kyoushitsu ni hairimasu", "I enter the classroom."),
				b200Sentence("門の前にいます", "もんのまえにいます", "mon no mae ni imasu", "I am in front of the gate."),
			},
		},
		{
			Number: 13,
			Title:  "Movement Verbs",
			Kanji: []beginnerKanjiSeed{
				b200Kanji("開", "あ", "a", "open", "開けます", "あけます", "akemasu", "open something"),
				b200Kanji("閉", "し", "shi", "close", "閉めます", "しめます", "shimemasu", "close something"),
				b200Kanji("立", "た", "ta", "stand", "立ちます", "たちます", "tachimasu", "stand"),
				b200Kanji("座", "すわ", "suwa", "sit", "座ります", "すわります", "suwarimasu", "sit"),
				b200Kanji("歩", "ある", "aru", "walk", "歩きます", "あるきます", "arukimasu", "walk"),
				b200Kanji("走", "はし", "hashi", "run", "走ります", "はしります", "hashirimasu", "run"),
				b200Kanji("止", "と", "to", "stop", "止まります", "とまります", "tomarimasu", "stop"),
				b200Kanji("動", "うご", "ugo", "move", "動きます", "うごきます", "ugokimasu", "move"),
				b200Kanji("働", "はたら", "hatara", "work", "働きます", "はたらきます", "hatarakimasu", "work"),
				b200Kanji("作", "つく", "tsuku", "make", "作ります", "つくります", "tsukurimasu", "make"),
			},
			Sentences: []beginnerSentenceSeed{
				b200Sentence("門を開けます", "もんをあけます", "mon o akemasu", "I open the gate."),
				b200Sentence("部屋の中で座ります", "へやのなかですわります", "heya no naka de suwarimasu", "I sit inside the room."),
				b200Sentence("町を歩きます", "まちをあるきます", "machi o arukimasu", "I walk through town."),
				b200Sentence("車が止まります", "くるまがとまります", "kuruma ga tomarimasu", "The car stops."),
				b200Sentence("会社で働きます", "かいしゃではたらきます", "kaisha de hatarakimasu", "I work at a company."),
			},
		},
		{
			Number: 14,
			Title:  "Thinking And Learning",
			Kanji: []beginnerKanjiSeed{
				b200Kanji("使", "つか", "tsuka", "use", "使います", "つかいます", "tsukaimasu", "use"),
				b200Kanji("持", "も", "mo", "hold; have", "持ちます", "もちます", "mochimasu", "hold; have"),
				b200Kanji("待", "ま", "ma", "wait", "待ちます", "まちます", "machimasu", "wait"),
				b200Kanji("言", "い", "i", "say", "言います", "いいます", "iimasu", "say"),
				b200Kanji("思", "おも", "omo", "think; feel", "思います", "おもいます", "omoimasu", "think"),
				b200Kanji("知", "し", "shi", "know", "知ります", "しります", "shirimasu", "know; learn"),
				b200Kanji("勉", "べん", "ben", "study effort", "勉強", "べんきょう", "benkyou", "study"),
				b200Kanji("強", "きょう", "kyou", "strong", "勉強", "べんきょう", "benkyou", "study"),
				b200Kanji("教", "おし", "oshi", "teach", "教えます", "おしえます", "oshiemasu", "teach"),
				b200Kanji("習", "なら", "nara", "learn", "習います", "ならいます", "naraimasu", "learn"),
			},
			Sentences: []beginnerSentenceSeed{
				b200Sentence("日本語を勉強します", "にほんごをべんきょうします", "nihongo o benkyou shimasu", "I study Japanese."),
				b200Sentence("先生に日本語を習います", "せんせいににほんごをならいます", "sensei ni nihongo o naraimasu", "I learn Japanese from a teacher."),
				b200Sentence("友達を待ちます", "ともだちをまちます", "tomodachi o machimasu", "I wait for a friend."),
				b200Sentence("名前を言います", "なまえをいいます", "namae o iimasu", "I say my name."),
				b200Sentence("本を持ちます", "ほんをもちます", "hon o mochimasu", "I hold a book."),
			},
		},
		{
			Number: 15,
			Title:  "Questions And Writing",
			Kanji: []beginnerKanjiSeed{
				b200Kanji("考", "かんが", "kanga", "think", "考えます", "かんがえます", "kangaemasu", "think"),
				b200Kanji("答", "こた", "kota", "answer", "答えます", "こたえます", "kotaemasu", "answer"),
				b200Kanji("問", "もん", "mon", "question", "問題", "もんだい", "mondai", "problem; question"),
				b200Kanji("題", "だい", "dai", "topic; problem", "問題", "もんだい", "mondai", "problem; question"),
				b200Kanji("文", "ぶん", "bun", "sentence", "文", "ぶん", "bun", "sentence; text"),
				b200Kanji("字", "じ", "ji", "character", "文字", "もじ", "moji", "letter; character"),
				b200Kanji("英", "えい", "ei", "English", "英語", "えいご", "eigo", "English language"),
				b200Kanji("漢", "かん", "kan", "Chinese; Sino-", "漢字", "かんじ", "kanji", "kanji"),
				b200Kanji("料", "りょう", "ryou", "material; fee", "料理", "りょうり", "ryouri", "cooking; food"),
				b200Kanji("理", "り", "ri", "reason; logic", "料理", "りょうり", "ryouri", "cooking; food"),
			},
			Sentences: []beginnerSentenceSeed{
				b200Sentence("問題を考えます", "もんだいをかんがえます", "mondai o kangaemasu", "I think about the problem."),
				b200Sentence("答えを書きます", "こたえをかきます", "kotae o kakimasu", "I write the answer."),
				b200Sentence("漢字を読みます", "かんじをよみます", "kanji o yomimasu", "I read kanji."),
				b200Sentence("英語の文字を見ます", "えいごのもじをみます", "eigo no moji o mimasu", "I look at English letters."),
				b200Sentence("料理を作ります", "りょうりをつくります", "ryouri o tsukurimasu", "I cook food."),
			},
		},
		{
			Number: 16,
			Title:  "Food And Morning",
			Kanji: []beginnerKanjiSeed{
				b200Kanji("茶", "ちゃ", "cha", "tea", "お茶", "おちゃ", "ocha", "tea"),
				b200Kanji("肉", "にく", "niku", "meat", "肉", "にく", "niku", "meat"),
				b200Kanji("牛", "うし", "ushi", "cow", "牛肉", "ぎゅうにく", "gyuuniku", "beef"),
				b200Kanji("鳥", "とり", "tori", "bird", "鳥", "とり", "tori", "bird"),
				b200Kanji("米", "こめ", "kome", "rice", "米", "こめ", "kome", "rice"),
				b200Kanji("野", "の", "no", "field", "野菜", "やさい", "yasai", "vegetables"),
				b200Kanji("菜", "さい", "sai", "vegetable", "野菜", "やさい", "yasai", "vegetables"),
				b200Kanji("果", "か", "ka", "fruit", "果物", "くだもの", "kudamono", "fruit"),
				b200Kanji("物", "もの", "mono", "thing", "果物", "くだもの", "kudamono", "fruit"),
				b200Kanji("朝", "あさ", "asa", "morning", "朝", "あさ", "asa", "morning"),
			},
			Sentences: []beginnerSentenceSeed{
				b200Sentence("朝にお茶を飲みます", "あさにおちゃをのみます", "asa ni ocha o nomimasu", "I drink tea in the morning."),
				b200Sentence("牛肉と野菜を食べます", "ぎゅうにくとやさいをたべます", "gyuuniku to yasai o tabemasu", "I eat beef and vegetables."),
				b200Sentence("鳥を見ます", "とりをみます", "tori o mimasu", "I see a bird."),
				b200Sentence("米を買います", "こめをかいます", "kome o kaimasu", "I buy rice."),
				b200Sentence("果物があります", "くだものがあります", "kudamono ga arimasu", "There is fruit."),
			},
		},
		{
			Number: 17,
			Title:  "Seasons And Distance",
			Kanji: []beginnerKanjiSeed{
				b200Kanji("昼", "ひる", "hiru", "daytime; noon", "昼", "ひる", "hiru", "daytime; lunch"),
				b200Kanji("夜", "よる", "yoru", "night", "夜", "よる", "yoru", "night"),
				b200Kanji("晩", "ばん", "ban", "evening", "今晩", "こんばん", "konban", "tonight"),
				b200Kanji("春", "はる", "haru", "spring", "春", "はる", "haru", "spring"),
				b200Kanji("夏", "なつ", "natsu", "summer", "夏", "なつ", "natsu", "summer"),
				b200Kanji("秋", "あき", "aki", "autumn", "秋", "あき", "aki", "autumn"),
				b200Kanji("冬", "ふゆ", "fuyu", "winter", "冬", "ふゆ", "fuyu", "winter"),
				b200Kanji("明", "あか", "aka", "bright", "明るい", "あかるい", "akarui", "bright"),
				b200Kanji("暗", "くら", "kura", "dark", "暗い", "くらい", "kurai", "dark"),
				b200Kanji("近", "ちか", "chika", "near", "近い", "ちかい", "chikai", "near"),
			},
			Sentences: []beginnerSentenceSeed{
				b200Sentence("昼に学校へ行きます", "ひるにがっこうへいきます", "hiru ni gakkou e ikimasu", "I go to school at noon."),
				b200Sentence("夜は暗いです", "よるはくらいです", "yoru wa kurai desu", "Night is dark."),
				b200Sentence("春と夏が好きです", "はるとなつがすきです", "haru to natsu ga suki desu", "I like spring and summer."),
				b200Sentence("秋と冬に雨が多いです", "あきとふゆにあめがおおいです", "aki to fuyu ni ame ga ooi desu", "There is a lot of rain in autumn and winter."),
				b200Sentence("近い店へ行きます", "ちかいみせへいきます", "chikai mise e ikimasu", "I go to a nearby shop."),
			},
		},
		{
			Number: 18,
			Title:  "Contrast And Condition",
			Kanji: []beginnerKanjiSeed{
				b200Kanji("遠", "とお", "too", "far", "遠い", "とおい", "tooi", "far"),
				b200Kanji("広", "ひろ", "hiro", "wide", "広い", "ひろい", "hiroi", "wide"),
				b200Kanji("狭", "せま", "sema", "narrow", "狭い", "せまい", "semai", "narrow"),
				b200Kanji("弱", "よわ", "yowa", "weak", "弱い", "よわい", "yowai", "weak"),
				b200Kanji("好", "す", "su", "like", "好き", "すき", "suki", "likeable; favorite"),
				b200Kanji("悪", "わる", "waru", "bad", "悪い", "わるい", "warui", "bad"),
				b200Kanji("正", "ただ", "tada", "correct", "正しい", "ただしい", "tadashii", "correct"),
				b200Kanji("元", "げん", "gen", "origin; health", "元気", "げんき", "genki", "healthy; energetic"),
				b200Kanji("有", "ゆう", "yuu", "have; exist", "有名", "ゆうめい", "yuumei", "famous"),
				b200Kanji("無", "な", "na", "nothing", "無い", "ない", "nai", "not exist"),
			},
			Sentences: []beginnerSentenceSeed{
				b200Sentence("遠い町へ行きます", "とおいまちへいきます", "tooi machi e ikimasu", "I go to a far town."),
				b200Sentence("広い部屋で勉強します", "ひろいへやでべんきょうします", "hiroi heya de benkyou shimasu", "I study in a wide room."),
				b200Sentence("狭い道を歩きます", "せまいみちをあるきます", "semai michi o arukimasu", "I walk on a narrow road."),
				b200Sentence("元気な犬がいます", "げんきないぬがいます", "genki na inu ga imasu", "There is an energetic dog."),
				b200Sentence("正しい答えを書きます", "ただしいこたえをかきます", "tadashii kotae o kakimasu", "I write the correct answer."),
			},
		},
		{
			Number: 19,
			Title:  "Order And Sound",
			Kanji: []beginnerKanjiSeed{
				b200Kanji("事", "こと", "koto", "thing; matter", "事", "こと", "koto", "thing; matter"),
				b200Kanji("方", "かた", "kata", "way; person", "読み方", "よみかた", "yomikata", "way of reading"),
				b200Kanji("同", "おな", "ona", "same", "同じ", "おなじ", "onaji", "same"),
				b200Kanji("別", "べつ", "betsu", "different", "別の", "べつの", "betsu no", "another; different"),
				b200Kanji("次", "つぎ", "tsugi", "next", "次", "つぎ", "tsugi", "next"),
				b200Kanji("最", "さい", "sai", "most", "最初", "さいしょ", "saisho", "beginning; first"),
				b200Kanji("初", "はじ", "haji", "first", "初めて", "はじめて", "hajimete", "for the first time"),
				b200Kanji("終", "お", "o", "end", "終わります", "おわります", "owarimasu", "end; finish"),
				b200Kanji("色", "いろ", "iro", "color", "色", "いろ", "iro", "color"),
				b200Kanji("音", "おと", "oto", "sound", "音", "おと", "oto", "sound"),
			},
			Sentences: []beginnerSentenceSeed{
				b200Sentence("次の問題を読みます", "つぎのもんだいをよみます", "tsugi no mondai o yomimasu", "I read the next problem."),
				b200Sentence("最初に名前を書きます", "さいしょになまえをかきます", "saisho ni namae o kakimasu", "I write my name first."),
				b200Sentence("同じ色を見ます", "おなじいろをみます", "onaji iro o mimasu", "I see the same color."),
				b200Sentence("別の音を聞きます", "べつのおとをききます", "betsu no oto o kikimasu", "I hear a different sound."),
				b200Sentence("勉強が終わります", "べんきょうがおわります", "benkyou ga owarimasu", "Study ends."),
			},
		},
		{
			Number: 20,
			Title:  "Travel And Health",
			Kanji: []beginnerKanjiSeed{
				b200Kanji("楽", "たの", "tano", "fun; comfort", "楽しい", "たのしい", "tanoshii", "fun"),
				b200Kanji("歌", "うた", "uta", "song", "歌", "うた", "uta", "song"),
				b200Kanji("写", "しゃ", "sha", "copy; photo", "写真", "しゃしん", "shashin", "photo"),
				b200Kanji("真", "しん", "shin", "true", "写真", "しゃしん", "shashin", "photo"),
				b200Kanji("旅", "たび", "tabi", "travel", "旅", "たび", "tabi", "travel"),
				b200Kanji("病", "びょう", "byou", "sick", "病院", "びょういん", "byouin", "hospital"),
				b200Kanji("院", "いん", "in", "institution", "病院", "びょういん", "byouin", "hospital"),
				b200Kanji("薬", "くすり", "kusuri", "medicine", "薬", "くすり", "kusuri", "medicine"),
				b200Kanji("医", "い", "i", "doctor; medicine", "医者", "いしゃ", "isha", "doctor"),
				b200Kanji("者", "しゃ", "sha", "person", "医者", "いしゃ", "isha", "doctor"),
			},
			Sentences: []beginnerSentenceSeed{
				b200Sentence("楽しい歌を聞きます", "たのしいうたをききます", "tanoshii uta o kikimasu", "I listen to a fun song."),
				b200Sentence("写真を見ます", "しゃしんをみます", "shashin o mimasu", "I look at a photo."),
				b200Sentence("旅で海へ行きます", "たびでうみへいきます", "tabi de umi e ikimasu", "I go to the sea on a trip."),
				b200Sentence("病院で薬をもらいます", "びょういんでくすりをもらいます", "byouin de kusuri o moraimasu", "I receive medicine at the hospital."),
				b200Sentence("医者に会います", "いしゃにあいます", "isha ni aimasu", "I meet a doctor."),
			},
		},
	}
}

func b200Kanji(char, kana, romaji, meaning, word, wordKana, wordRomaji, wordMeaning string) beginnerKanjiSeed {
	return beginnerKanjiSeed{
		Char:        char,
		Kana:        kana,
		Romaji:      romaji,
		Meaning:     meaning,
		Word:        word,
		WordKana:    wordKana,
		WordRomaji:  wordRomaji,
		WordMeaning: wordMeaning,
	}
}

func b200Sentence(text, kana, romaji, meaning string) beginnerSentenceSeed {
	return beginnerSentenceSeed{
		Text:    text,
		Kana:    kana,
		Romaji:  romaji,
		Meaning: meaning,
		Tree: []treeNoteSeed{
			{Label: "sentence", Body: meaning},
			{Label: "reading", Body: fmt.Sprintf("%s = %s", text, kana)},
		},
	}
}
