package atoms

import (
	"strings"
	"unicode"
	"unicode/utf8"
)

// StripANSI removes CSI color/control sequences generated by this package.
func StripANSI(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); {
		if s[i] == '\x1b' && i+1 < len(s) && s[i+1] == '[' {
			i += 2
			for i < len(s) {
				if s[i] >= 0x40 && s[i] <= 0x7e {
					i++
					break
				}
				i++
			}
			continue
		}

		r, size := utf8.DecodeRuneInString(s[i:])
		b.WriteRune(r)
		i += size
	}
	return b.String()
}

// DisplayWidth returns terminal cell width, counting common Japanese glyphs as
// double-width so kana and kanji stay aligned inside ASCII frames.
func DisplayWidth(s string) int {
	width := 0
	for _, r := range StripANSI(s) {
		width += runeWidth(r)
	}
	return width
}

// FitDisplay returns text padded or truncated to exactly width terminal cells.
func FitDisplay(s string, width int) string {
	if width <= 0 {
		return ""
	}

	s = StripANSI(s)
	if DisplayWidth(s) > width {
		s = TruncateDisplay(s, width)
	}
	return s + strings.Repeat(" ", width-DisplayWidth(s))
}

// TruncateDisplay trims text without splitting a wide glyph across the boundary.
func TruncateDisplay(s string, width int) string {
	if width <= 0 {
		return ""
	}

	var b strings.Builder
	used := 0
	for _, r := range StripANSI(s) {
		rw := runeWidth(r)
		if used+rw > width {
			break
		}
		b.WriteRune(r)
		used += rw
	}
	return b.String()
}

func runeWidth(r rune) int {
	switch {
	case r == '\t':
		return 4
	case r == '\n' || r == '\r':
		return 0
	case r < 32 || (r >= 0x7f && r < 0xa0):
		return 0
	case unicode.Is(unicode.Mn, r) || unicode.Is(unicode.Me, r):
		return 0
	case isWideRune(r):
		return 2
	default:
		return 1
	}
}

func isWideRune(r rune) bool {
	return (r >= 0x1100 && r <= 0x115f) ||
		(r >= 0x2329 && r <= 0x232a) ||
		(r >= 0x2e80 && r <= 0xa4cf) ||
		(r >= 0xac00 && r <= 0xd7a3) ||
		(r >= 0xf900 && r <= 0xfaff) ||
		(r >= 0xfe10 && r <= 0xfe19) ||
		(r >= 0xfe30 && r <= 0xfe6f) ||
		(r >= 0xff00 && r <= 0xff60) ||
		(r >= 0xffe0 && r <= 0xffe6)
}
